version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=pisma
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    environment:
      - PISMA_DJANGO_SQL_ENGINE=django.db.backends.postgresql
      - PISMA_DATABASE_URL=postgres://postgres:postgres@db/pisma
      - PISMA_PORT=8888
    command: python server.py
    ports:
      - "8888:8888"
    depends_on:
      - db
