version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=pisma
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - static_volume:/code/staticfiles
    environment:
      - PISMA_DJANGO_SQL_ENGINE=django.db.backends.postgresql
      - PISMA_DATABASE_URL=postgres://postgres:postgres@db/pisma
      - PISMA_PORT=8888
      - PISMA_DJANGO_SELF_SERVE_STATIC_FILES=Flase
    command: python server.py
    expose:
      - 8888
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
